"""create favorite resources

Revision ID: 2e519fbcd2a4
Revises: 3f1c11a14560
Create Date: 2026-06-24 21:29:10.824735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e519fbcd2a4'
down_revision: Union[str, Sequence[str], None] = '3f1c11a14560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_id', name='uq_favorite_resource_user_resource')
    )
    op.create_index(op.f('ix_favorite_resources_resource_id'), 'favorite_resources', ['resource_id'], unique=False)
    op.create_index(op.f('ix_favorite_resources_user_id'), 'favorite_resources', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorite_resources_user_id'), table_name='favorite_resources')
    op.drop_index(op.f('ix_favorite_resources_resource_id'), table_name='favorite_resources')
    op.drop_table('favorite_resources')
    # ### end Alembic commands ###
