"""add availability exceptions

Revision ID: 31aa8fa77d5c
Revises: 633c9a33be79
Create Date: 2026-07-13 17:45:03.737629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31aa8fa77d5c'
down_revision: Union[str, Sequence[str], None] = '633c9a33be79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_exceptions_end_time'), 'availability_exceptions', ['end_time'], unique=False)
    op.create_index(op.f('ix_availability_exceptions_resource_id'), 'availability_exceptions', ['resource_id'], unique=False)
    op.create_index(op.f('ix_availability_exceptions_start_time'), 'availability_exceptions', ['start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_availability_exceptions_start_time'), table_name='availability_exceptions')
    op.drop_index(op.f('ix_availability_exceptions_resource_id'), table_name='availability_exceptions')
    op.drop_index(op.f('ix_availability_exceptions_end_time'), table_name='availability_exceptions')
    op.drop_table('availability_exceptions')
    # ### end Alembic commands ###
