"""create resource reviews

Revision ID: 5e96fb4670d0
Revises: 2e519fbcd2a4
Create Date: 2026-06-25 13:46:16.060243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e96fb4670d0'
down_revision: Union[str, Sequence[str], None] = '2e519fbcd2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resource_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'resource_id', name='uq_resource_review_user_resource')
    )
    op.create_index(op.f('ix_resource_reviews_resource_id'), 'resource_reviews', ['resource_id'], unique=False)
    op.create_index(op.f('ix_resource_reviews_user_id'), 'resource_reviews', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resource_reviews_user_id'), table_name='resource_reviews')
    op.drop_index(op.f('ix_resource_reviews_resource_id'), table_name='resource_reviews')
    op.drop_table('resource_reviews')
    # ### end Alembic commands ###
