"""create availability rules

Revision ID: 633c9a33be79
Revises: 5e96fb4670d0
Create Date: 2026-07-13 16:32:26.860240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '633c9a33be79'
down_revision: Union[str, Sequence[str], None] = '5e96fb4670d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id', 'weekday', 'start_time', 'end_time', name='uq_availability_rule_interval')
    )
    op.create_index(op.f('ix_availability_rules_resource_id'), 'availability_rules', ['resource_id'], unique=False)
    op.create_index(op.f('ix_availability_rules_weekday'), 'availability_rules', ['weekday'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_availability_rules_weekday'), table_name='availability_rules')
    op.drop_index(op.f('ix_availability_rules_resource_id'), table_name='availability_rules')
    op.drop_table('availability_rules')
    # ### end Alembic commands ###
