"""create reservations

Revision ID: 866c24060d5e
Revises: 325c342a8d55
Create Date: 2026-05-28 20:26:21.633419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866c24060d5e'
down_revision: Union[str, Sequence[str], None] = '325c342a8d55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_end_time'), 'reservations', ['end_time'], unique=False)
    op.create_index(op.f('ix_reservations_resource_id'), 'reservations', ['resource_id'], unique=False)
    op.create_index(op.f('ix_reservations_start_time'), 'reservations', ['start_time'], unique=False)
    op.create_index(op.f('ix_reservations_user_id'), 'reservations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_user_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_start_time'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_resource_id'), table_name='reservations')
    op.drop_index(op.f('ix_reservations_end_time'), table_name='reservations')
    op.drop_table('reservations')
    # ### end Alembic commands ###
