import { expect, test } from "./fixtures";
import type { PropertyListing } from "../src/property-types";
import { propertyToday, shiftDate } from "../src/stay-types";

test("owner saves a season and guest books its itemized price across the season boundary", async ({ page }, testInfo) => {
  const arrival = shiftDate(propertyToday(), 3);
  const seasonEnd = shiftDate(arrival, 2);
  const departure = shiftDate(arrival, 3);
  let listing: PropertyListing = { id: 7, venue_id: 1, title: "Stan sa letnjom cenom", description: "Udoban stan u centru sa prostranom terasom.", city: "Beograd", offer_type: "short_stay", area_sqm: 60, rooms: 2, price_cents: 6500, currency: "EUR", contact_email: "owner@example.com", is_published: true, booking_enabled: true, minimum_nights: 1, maximum_nights: 90, seasonal_rates: [] };
  const nightlyPrices = [{ date: arrival, price_cents: 10000 }, { date: shiftDate(arrival, 1), price_cents: 10000 }, { date: seasonEnd, price_cents: 6500 }];
  const stay = { id: 42, property_id: 7, title: listing.title, city: listing.city, contact_email: listing.contact_email, timezone: "Europe/Belgrade", check_in: arrival, check_out: departure, guests: 2, status: "confirmed", nightly_rate_cents: 6500, nightly_prices: nightlyPrices, total_cents: 26500, currency: "EUR", payment_method: "pay_on_arrival", created_at: new Date().toISOString() };
  await page.route("**/api/auth/me", route => route.fulfill({ json: { id: 1, email: "owner@example.com", role: "owner" } }));
  await page.route("**/api/venues", route => route.fulfill({ json: [] }));
  await page.route("**/api/promotions/active", route => route.fulfill({ json: [] }));
  await page.route("**/api/owner/stats", route => route.fulfill({ json: { total_venues: 1, total_resources: 0, total_reservations: 0, total_revenue_cents: 0, reservations_by_status: {}, top_resources: [] } }));
  await page.route("**/api/owner/venues", route => route.fulfill({ json: [{ id: 1, name: "Moj stan", address: "Centar", description: null, owner_id: 1 }] }));
  await page.route("**/api/owner/resources", route => route.fulfill({ json: [] }));
  await page.route("**/api/owner/reservations", route => route.fulfill({ json: [] }));
  await page.route("**/api/owner/properties?*", route => route.fulfill({ json: { items: [listing], total: 1, limit: 20, offset: 0, has_next: false } }));
  await page.route("**/api/properties/7", route => {
    if (route.request().method() === "PUT") listing = { ...route.request().postDataJSON(), id: 7 };
    return route.fulfill({ json: listing });
  });
  await page.route("**/api/properties?*", route => route.fulfill({ json: { items: [{ ...listing, stay_total_cents: 26500 }], total: 1, limit: 12, offset: 0, has_next: false } }));
  await page.route("**/api/properties/7/views", route => route.fulfill({ status: 204 }));
  await page.route("**/api/properties/7/reviews?*", route => route.fulfill({ json: { items: [], total: 0, average_rating: null, has_next: false } }));
  await page.route("**/api/properties/7/calendar?*", route => route.fulfill({ json: { start: arrival, end: departure, occupied: [] } }));
  await page.route("**/api/properties/7/stay-quote", route => route.fulfill({ json: { nights: 3, nightly_prices: nightlyPrices, nightly_rate_cents: 6500, total_cents: 26500, currency: "EUR", timezone: "Europe/Belgrade", payment_method: "pay_on_arrival" } }));
  await page.route("**/api/properties/7/stays", route => {
    expect(route.request().postDataJSON()).toMatchObject({ check_in: arrival, check_out: departure, expected_total_cents: 26500, expected_nightly_prices: nightlyPrices });
    return route.fulfill({ status: 201, json: stay });
  });
  await page.route("**/api/stays/mine?*", route => route.fulfill({ json: { items: [stay], total: 1, has_next: false } }));
  await page.goto("/owner");
  await page.getByRole("button", { name: `Izmeni: ${listing.title}` }).click();
  await page.getByRole("button", { name: "Dodaj sezonski period" }).click();
  await page.getByLabel("Naziv perioda", { exact: true }).fill("Sezona");
  await page.getByLabel("Prva noć", { exact: true }).fill(arrival);
  await page.getByLabel("Do datuma (nije uključen)", { exact: true }).fill(seasonEnd);
  await page.getByLabel("Sezonska cena po noći", { exact: true }).fill("100");
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.locator(".seasonal-editor").screenshot({ path: testInfo.outputPath("seasonal-editor-mobile.png") });
  await page.getByRole("button", { name: "Sačuvaj oglas" }).click();
  await expect(page.getByText("Oglas je objavljen na naslovnoj strani.")).toBeVisible();
  expect(listing.seasonal_rates).toEqual([{ start: arrival, end: seasonEnd, price_cents: 10000, label: "Sezona" }]);
  await page.goto(`/?offer_type=short_stay&check_in=${arrival}&check_out=${departure}&guests=2`);
  await expect(page.locator(".ph-card-bottom")).toContainText("265,00");
  await expect(page.locator(".ph-card-bottom")).toContainText("boravak");
  await page.getByRole("link", { name: listing.title, exact: true }).click();
  await page.getByRole("button", { name: "Proveri dostupnost i cenu" }).click();
  await page.getByText("Obračun po noćima (3)", { exact: true }).click();
  await expect(page.getByRole("table")).toContainText("65,00");
  await page.locator(".stay-quote").screenshot({ path: testInfo.outputPath("seasonal-quote-mobile.png") });
  await page.getByRole("button", { name: "Potvrdi rezervaciju" }).click();
  await expect(page.getByText(/Rezervacija je potvrđena/)).toBeVisible();
  listing = { ...listing, price_cents: 15000, seasonal_rates: [] };
  await page.getByRole("link", { name: /Pregledaj svoje boravke/ }).click();
  await page.getByText("Obračun po noćima (3)", { exact: true }).click();
  await expect(page.getByRole("table")).toContainText("100,00");
  await expect(page.getByRole("table")).toContainText("65,00");
  await expect(page.locator(".stay-row")).toContainText("265,00");
});
